before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
blobs:
  - provider: s3
    region: eu-west-1
    bucket: cyclopes
archives:
  - format: binary
    name_template: "cyclopes-{{.Os}}-{{.Arch}}-{{.Version}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
