version: "3"

env:
  FILENAME: cyclopes

tasks:
  build-linux:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o binaries/$FILENAME-linux *.go
  build-macos:
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -o binaries/$FILENAME-macos *.go
  build-windows:
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o binaries/$FILENAME-windows.exe *.go
